### ISSUE TITLE
Help with available rotate + left sidebar (preview pages) functionality

### ISSUE THREAD

**Issue by athomevastgoed** [teambition/pdfviewer#8]
Hi there,

We are using the PDF Viewer to open and show PDF files in a preview window. 
We have the following 2 questions:

- Rotating. We noticed the rotating functionality for rotating PDF files, which is great. However, when we have rotated a PDF file, we would want to save the results (newly rotated PDF) and overwrite the existing PDF file. Is saving this rotated result to a new PDF file support? Please let us know and how we should implement such.

- Left sidebar with previews / icons of the pages within the PDF. 
We noticed this functionality to open up the left sidebar and show how many pages (with small previews) the PDF has. Is there a setting where we can always open the PDF viewer with this left sidebar (incl. small previews) enabled by default?

Hope to hear from any of you soon. 

Thank you in advance!

Kind regards,
Mark

At Home Vastgoed
The Netherlands

**Comment by Boshen** [comment]
Hi @athomevastgoed 

viewer.js within this repo is a trimmed down version of https://github.com/mozilla/pdf.js/blob/master/web/viewer.js, from https://github.com/mozilla/pdf.js/tree/master/web

I suggest you to take a look there.

Cheers.

**Comment by athomevastgoed** [comment]
Thanks for your answer, we’re gonna take a look there, hope we can proceed from there.

Op 29 mei 2018, om 07:49 heeft Boshen <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi @athomevastgoed<https://github.com/athomevastgoed>

viewer.js within this repo is a trimmed down version of https://github.com/mozilla/pdf.js/blob/master/web/viewer.js, from https://github.com/mozilla/pdf.js/tree/master/web

I suggest you to take a look there.

Cheers.

**Comment by zensh** [comment]
😆
